### PR TITLE
[ENH]  Update to v2 API, flatten v2 module, improve concurrency.

### PR DESCRIPTION
**Pull request by rescrv**
Update to the chroma_cloud v2 API and in the process remove the v2
namespacing from the API.  Improve concurrency as well so that there's
no contention within libssl for requests using the same
collection/client object.

### CODE REVIEW

**Review by Anush008 — APPROVED** [review]
Great. Thanks @rescrv.
Could you please update the snippets in the README.md to reflect the changes?

**Comment by rescrv** [comment]
@Anush008 I've updated the README.  Would you consider a change to include the readme at the top of lib.rs so that the docs and readme come from the same source?  Something like this:  https://github.com/rescrv/blue/blob/main/guacamole/src/lib.rs#L1

**Comment by Anush008** [comment]
> Something like this: https://github.com/rescrv/blue/blob/main/guacamole/src/lib.rs#L1

👍. Thank you. That's cool.

**Comment by Anush008** [comment]
Hey @rescrv. I'll cut a release for the time being.
Thanks for taking the to contribute.

**Pull request merged**
